### ISSUE TITLE
Does it support face recognition?

### ISSUE THREAD

**Issue by gclsoft** [didi/delta#14]

**Comment by applenob** [comment]
Not yet. Delta supports NLP and speech tasks now.

**Comment by zh794390558** [comment]
It is easy to support face recognition, welcome to contributing.

**Comment by gclsoft** [comment]
How to support face recognition? Like this: https://github.com/AKSHAYUBHAT/DeepVideoAnalytics




------------------ 原始邮件 ------------------
发件人: "Hui Zhang"<notifications@github.com>; 
发送时间: 2019年8月14日(星期三) 下午2:54
收件人: "didi/delta"<delta@noreply.github.com>; 
抄送: "甘传立"<gclsoft@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [didi/delta] Does it support face recognition? (#14)




It is easy to support face recognition, welcome to contributing.
 
&mdash;
