### ISSUE TITLE
does delta work on tf<1.13.0 ?

### ISSUE THREAD

**Issue by nlp4whp** [didi/delta#15]
thus tf 1.13.0 needs CUDA 10.0 ....

**Comment by zh794390558** [comment]
Same tf api may not compatible.  DELTA has tested on tf1.14, and 1.13 may be OK.

**Comment by nlp4whp** [comment]
> Same tf api may not compatible. DELTA has tested on tf1.14, and 1.13 may be OK.

alright, thanks 🙏
