### ISSUE TITLE
Loss of so Library：x_ops.so

### ISSUE THREAD

**Issue by lyw2019** [didi/delta#16]
ERROR:
tensorflow.python.framework.errors_impl.NotFoundError: /home/delta/delta/layers/ops/x_ops.so: cannot open shared object file: No such file or directory

**Comment by Susan19900316** [comment]
I got the same issue. How to fix the problem??

**Comment by hankun11** [comment]
@Susan19900316  You probably didn't compile the ops successfully. Could you run this line again 
and give more information if it fails: https://github.com/didi/delta/blob/master/tools/Makefile#L85

**Comment by Susan19900316** [comment]
@hankun11  I install Delta in steps like this:
 1. cd tools
 2. ./install/install-delta.sh nlp gpu
3. source activate delta-py3.6-tf1.14
4. cd ..
5. source env.sh
6. pushd egs/mock_text_cls_data/text_cls/v1
7../run.sh

In the seventh step, i had two problems. The first one is that some python libraries, such like matplotlib,hurry, hurry.filesize and pyyaml,  haven't been installed. The second one is the loss of x_ops.so. The details follow:
-------------------------------------------------------------------
./run.sh          
------------------------------------------------------------------
/bin/bash: /home/Software/miniconda/envs/robot_pytorch/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "local/generate_mock_data.py", line 19, in <module>
    from delta.data.utils.test_utils import mock_a_text_file
  File "/home/Projects/delta/delta/data/utils/__init__.py", line 17, in <module>
    from delta.data.utils.common_utils import *
  File "/home/Projects/delta/delta/data/utils/common_utils.py", line 26, in <module>
    from delta.data.preprocess.text_ops import tokenize_label
  File "/home/Projects/delta/delta/data/preprocess/text_ops.py", line 22, in <module>
    from delta.layers.ops import py_x_ops
  File "/home/Projects/delta/delta/layers/__init__.py", line 27, in <module>
    from delta.layers.common_layers import *
  File "/home/Projects/delta/delta/layers/common_layers.py", line 22, in <module>
    from delta.data.feat import speech_ops
  File "/home/Projects/delta/delta/data/feat/__init__.py", line 17, in <module>
    from delta.data.feat import speech_ops
  File "/home/Projects/delta/delta/data/feat/speech_ops.py", line 25, in <module>
    from delta.layers.ops import py_x_ops
  File "/home/Projects/delta/delta/layers/ops/py_x_ops.py", line 27, in <module>
    tf.compat.v1.resource_loader.get_path_to_datafile('x_ops.so'))
  File "/home/Software/miniconda/envs/delta-py3.6-tf1.14/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/Projects/delta/delta/layers/ops/x_ops.so: cannot open shared object file: No such file or directory

**Comment by Susan19900316** [comment]
@hankun11  Sorry. I have fixed the issue. Something wrong appeared in the step 'make', but i did not found.
