### ISSUE TITLE
gcc version(20160609) not compatiable with tf compile version(7.3.1)

### ISSUE THREAD

**Issue by YanDongchao** [didi/delta#181]
安装full version 进行到最后时出现上述报错，看了一下自己的系统版本时ubuntu16.04  gcc版本是5.4.0
请问需要升级到哪个版本吗

**Comment by zh794390558** [comment]
是的，需要升级。不升级的话 custom ops 会出现运行时错误，得保持和 tensorflow pip 编译链一致。

**Comment by zh794390558** [comment]
Feel free to reopen this issue if needed.
