### ISSUE TITLE
deployment compile error

### ISSUE THREAD

**Issue by yunzhongyan0** [didi/delta#187]
**Describe the bug**
run 'run.sh' in directory dpl. Error occurs when compiling deltann. 

**Screenshots**
![image](https://user-images.githubusercontent.com/37043971/70291282-a2077900-1815-11ea-9d33-40525613582d.png)

what's the matter ?
**Additional context**
It's better to provide demos about how to deployment.  Do you have the plan?

**Comment by hankun11** [comment]
cc @mabaochang @itamaker  Please take a look at this issue.

**Comment by itamaker** [comment]
@yunzhongyan0 
- Is your compilation environment using a deltann docker image ?
- Please confirm that tools/install/install-deltann.sh is successfully executed in the delta directory.

**Comment by zh794390558** [comment]
more info https://github.com/didi/delta/pull/189
