### ISSUE TITLE
Is it still actively developed?

### ISSUE THREAD

**Issue by csukuangfj** [didi/delta#197]
More than two months have passed and there is no new commit.
Is the project still be developed?

By the way, why is Tensorflow selected for this project?

---

There is only one ASR benchmark, which is considerably smaller than the number of
NLP benchmarks. Is this project mainly used for NLP ?

**Comment by applenob** [comment]
Yes, we will keep on developing this repo. Our platform mainly focus on industry application. That's why we choose Tensorflow.
