### ISSUE TITLE
无法在Win10系统下安装

### ISSUE THREAD

**Issue by zhao-clive** [didi/delta#205]
怎么在windows下安装呢？Win10 GPU
(delta-pip-py3.6) C:\WINDOWS\system32>pip install delta-nlp
Looking in indexes: https://mirrors.ustc.edu.cn/pypi/web/simple, https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='mirrors.ustc.edu.cn', port=443): Read timed out. (read timeout=15)",)': /pypi/web/simple/delta-nlp/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='mirrors.ustc.edu.cn', port=443): Read timed out. (read timeout=15)",)': /pypi/web/simple/delta-nlp/
ERROR: Could not find a version that satisfies the requirement delta-nlp (from versions: none)
ERROR: No matching distribution found for delta-nlp
![installbug](https://user-images.githubusercontent.com/17791014/78316601-a315a080-7592-11ea-95a7-55828631b327.png)

**Comment by applenob** [comment]
抱歉，当前不支持在Windows系统下直接使用。
