### ISSUE TITLE
raw_solver get ZeroDivisionError

### ISSUE THREAD

**Issue by bycxw** [didi/delta#209]
**Describe the bug**
In delta/utils/solver/raw_solver.py 284-286:
logging.info("Evaluation rate of "
                       "progress: [ {:.2%} ]".format(
                           i / (num_batch_every_epoch - 1)))
If infer data size is less than or equal to batch size, num_batch_every_epoch - 1 will be zero.

**Comment by zh794390558** [comment]
welcome a bug fix, thx.

**Comment by zh794390558** [comment]
please reopen this if need.
