### ISSUE TITLE
是否有包含align-multimodal的docker镜像？

### ISSUE THREAD

**Issue by lessonxmk** [didi/delta#227]
您好，
我想在IEMOCAP数据集上测试align-multimodal模型，
我通过docker pull zh794390558/delta:delta-gpu-py3 下载了镜像，但是它似乎并不包含align-multimodal的相关内容
例如在delta/egs/iemocap/emo/v1/conf/下没有multimodal-align-emotion.yml文件，模型里也没有multimodal_cls_model.py等代码
我尝试仿照github上的代码手动添加这些内容，但是失败了
请问是否能发布一个包含上述内容的docker镜像？（由于在我的系统中无法直接安装，只能使用docker镜像）
谢谢

**Comment by hankun11** [comment]
@xhyandwyy

**Comment by xhyandwyy** [comment]
请问你手动添加遇到什么问题呢？我们可以考虑加到docker 镜像中

**Comment by lessonxmk** [comment]
我在‘/workspace/delta/delta/layers/‘目录下添加了sub_tf.py，用来添加MultiHeadAttention层，并在‘/workspace/delta/delta/layers/\__init\__.py'添加了‘from delta.layers.sub_tf import *’，之后执行'/workspace/delta/egs/iemocap/emo/v1/run_mm.sh'出现了如下错误：
> [ 2020-08-04 08:53:26,557 INFO         main.py:65    33264 ]  Loading all modules ...
[ 2020-08-04 08:53:27,292 WARNING     register.py:180   33264 ]  Module text_cls_task import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,292 WARNING     register.py:180   33264 ]  Module text_seq_label_task import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,292 WARNING     register.py:180   33264 ]  Module text_match_task import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,292 WARNING     register.py:180   33264 ]  Module text_nlu_joint_task import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_seq2seq_task import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module speech_cls_task import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module speech_cls_task import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module speech_cls_rawmodel import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module speaker_cls_rawmodel import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module speech_cls_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module resnet_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_seq_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_hierarchical_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_seq_label_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_nlu_joint_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_seq_label_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_seq2seq_model import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_cls_preparer import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,293 WARNING     register.py:180   33264 ]  Module text_match_preparer import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,294 WARNING     register.py:180   33264 ]  Module text_seq_label_preparer import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,294 WARNING     register.py:180   33264 ]  Module text_nlu_joint_preparer import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,294 WARNING     register.py:180   33264 ]  Module text_seq2seq_preparer import failed: No module named 'delta.layers.utils_tf'
[ 2020-08-04 08:53:27,294 CRITICAL     register.py:181   33264 ]  Please check these modules.
F0804 08:53:27.294248 140129861687104 register.py:181] Please check these modules.
Fatal Python error: Aborted
Current thread 0x00007f7286a0d740 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/absl/logging/__init__.py", line 850 in emit
  File "/usr/lib/python3.6/logging/__init__.py", line 865 in handle
  File "/usr/local/lib/python3.6/dist-packages/absl/logging/__init__.py", line 900 in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1516 in callHandlers
  File "/usr/local/lib/python3.6/dist-packages/absl/logging/__init__.py", line 1064 in handle
  File "/usr/lib/python3.6/logging/__init__.py", line 1444 in _log
  File "/usr/lib/python3.6/logging/__init__.py", line 1374 in log
  File "/usr/local/lib/python3.6/dist-packages/absl/logging/__init__.py", line 1047 in log
  File "/usr/local/lib/python3.6/dist-packages/absl/logging/__init__.py", line 485 in log
  File "/usr/local/lib/python3.6/dist-packages/absl/logging/__init__.py", line 312 in fatal
  File "/workspace/delta/delta/utils/register.py", line 181 in _handle_errors
  File "/workspace/delta/delta/utils/register.py", line 225 in import_all_modules_for_register
  File "/workspace/delta/./delta/main.py", line 66 in main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250 in _run_main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299 in run
  File "/workspace/delta/./delta/main.py", line 114 in entry
  File "/workspace/delta/./delta/main.py", line 127 in <module>
run_mm.sh: line 60: 33264 Aborted                 (core dumped) python3 -u $MAIN_ROOT/delta/main.py --cmd train_and_eval --config $config_file
