### ISSUE TITLE
Example scripts for audio missing?

### ISSUE THREAD

**Issue by happypanda5** [didi/delta#24]
Hello, thank you for the toolkit

**Am I wrong to say that there are no example scripts to use Delta toolkit for audio applications?**

Without an example script, it is really difficult to test your toolkit.

**Comment by hankun11** [comment]
There are a couple of example scripts for audio applications, such as ASR, speaker verification, emotion recognition. Check this for details: https://github.com/didi/delta/blob/master/egs/README.md

**Comment by hankun11** [comment]
Meanwhile, we may need to add tutorials for these examples, similar to https://github.com/didi/delta/blob/master/docs/tutorials/text_class_example.md @zh794390558

**Comment by zh794390558** [comment]
cc @GaryGao99  Please add an emotion tutorial.

**Comment by zh794390558** [comment]
see https://github.com/didi/delta/blob/master/docs/tutorials/emotion_class_example.md
