### ISSUE TITLE
move arcface_loss to loss_utils

### ISSUE THREAD

**Issue by zh794390558** [didi/delta#30]
**Describe the solution you'd like**
Moving `def arcface_loss` to utils and support `weights` from outer and create inner.
And also add unit test.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hankun11** [comment]
See the comment @barius  
https://github.com/didi/delta/pull/37#commitcomment-34781880

**Comment by hankun11** [comment]
@barius  found that the conda installed tensorflow may have numeric issues. We need to use pip to install tensorflow.  @applenob please help to update the install scripts, thanks!
