### ISSUE TITLE
AttributeError: 'JointBilstmCrfModel' object has no attribute '_trainable_weights'

### ISSUE THREAD

**Issue by gallupliu** [didi/delta#33]
**Describe the bug**
in tf1.12, run python main.py --cmd train --config ../egs/atis2/nlu_joint/v1/config/nlu_joint.yml ,AttributeError: 'JointBilstmCrfModel' object has no attribute '_trainable_weights'
**To Reproduce**
AttributeError: 'JointBilstmCrfModel' object has no attribute '_trainable_weights'
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubuntu 18.04

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zh794390558** [comment]
Does test under `tf1.13` or `tf1.14`?

**Comment by gallupliu** [comment]
sorry,I only installed CUDA 9

**Comment by zh794390558** [comment]
If nvidia driver support CUDA10, you can try with this `https://github.com/didi/delta/blob/master/docs/installation/manual_setup.md#pip-install`.
