### ISSUE TITLE
using ops to implement steps/make_fbank_pitch.sh 

### ISSUE THREAD

**Issue by zh794390558** [didi/delta#61]
replace this cmd `steps/make_fbank_pitch.sh --cmd run.pl --nj 2 --write_utt2num_frames true data/test exp/make_fbank/test fbank` by ops

_Originally posted by @zh794390558 in https://github.com/didi/delta/pull/52#issuecomment-524861103_

ops:
https://github.com/didi/delta/tree/master/delta/layers/ops

feat:
https://github.com/didi/delta/tree/master/delta/data/feat

output:
put `make_fbank_pitch.sh` into `delta/utils`

reference:
https://github.com/espnet/espnet/tree/master/espnet/transform

**Comment by tjadamlee** [comment]
To remove the kaldi dependency
