### ISSUE TITLE
using conda and pip to instal tensorflow as default

### ISSUE THREAD

**Issue by zh794390558** [didi/delta#63]
**Is your feature request related to a problem? Please describe.**
using conda+pip to install tensorflow, and also fix README.md

**Describe the solution you'd like**
N/A.

**Describe alternatives you've considered**

**Additional context**
arcface loss unit test not pass using conda to install tensorflow, beacuse number precision which caused by Tensorflow Compile Flags. conda may re-compile tensorflow for source by itself and not support some SIMD for linux x86.

**Comment by antihj** [comment]
مرحبا  ان نبحت عل برنامج  اخترق  ايميل
