### ISSUE TITLE
如何部署模型？

### ISSUE THREAD

**Issue by dongyt2004** [didi/delta#93]
你好，我已经训练并导出了cnn_dailymail例子的saved_model模型，但我不知道如何部署我的模型并对外提供服务。我试图在tf-serving docker上部署，命令是docker run -d --name tf-serving -v /root/delta:/models/delta -e MODEL_NAME=delta tensorflow/serving:1.14.0，但报错。我的宿主机/root/delta目录下有我导出的saved_model模型，启动容器后查看日志，显示：tensorflow_serving/util/retrier.cc:37] Loading servable: {name: delta version: 1} failed: Not found: Op type not registered 'SentenceToIds' in binary running on hi2. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. 
此外，请详细帮我讲解一下如果这个text summarization例子部署成功，我该如何调用它为我返回文本摘要，上传什么参数，返回给我什么信息，部署时的model.yaml该怎么写，多谢！

**Comment by zh794390558** [comment]
目前 tfserving 对 custom op 支持不太友善，需要重新编译 tfserving 才可以用。建议用 deltann 来上线，对应的 server 也在开发中。具体文档请  @mabaochang 添加下，谢谢。

**Comment by dongyt2004** [comment]
> 目前 tfserving 对 custom op 支持不太友善，需要重新编译 tfserving 才可以用。建议用 deltann 上线，对应的 server 我们也在开发中。具体文档请 @mabaochang 添加下，谢谢。
> 
> refs:
> [tensorflow/serving#867](https://github.com/tensorflow/serving/issues/867)
> [tensorflow/custom-op#3](https://github.com/tensorflow/custom-op/issues/3)
> https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/custom_op.md

**Comment by dongyt2004** [comment]
请问有cnn_dailymail例子deltann部署的详细文档或说明吗？包括model.yaml该怎么写，谢谢。

**Comment by zh794390558** [comment]
现在没有。可以把模型放到 dpl/model 对应的文件中。model.yaml 可以参看 deltann/examples/text_cls/model.yaml 文件。

**Comment by zh794390558** [comment]
cc @mabaochang 请添加下 dpl 的文档。

**Comment by zh794390558** [comment]
dpl 文档已添加。
